version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - '8545:8545'

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: postgres
      postgres_port: 5432
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'matic:${MATIC_RPC_URL}'

  pgAdmin:
      image: dpage/pgadmin4:8.11.0
      restart: always
      user: root
      ports:
        - 8080:80
      environment:
        PGADMIN_DEFAULT_EMAIL: hi@example.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_CONFIG_SERVER_MODE: 'False'
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres

volumes:
  pgdata:
  pgadmin:
